--- 
apiVersion: v1
kind: Pod
metadata: 
  labels: 
    app: demo-voting-app
    name: postgres-pod
  name: postgres-pod
spec: 
  containers: 
    - 
      image: postgres:11.7
      name: postgres
      ports: 
        - 
          containerPort: 5432
