apiVersion: v1
kind: Pod
metadata:
  name: netcore-app-pod
  labels:
    name: netcore-app-pod
    app: netcore-app
spec:
  containers:
  - name: netcore
    image: mohanaveluk/aspcoreondocker:v1.0
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
