apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
  labels:
    app: node-application
spec:
  replicas: 1
  selector:
    matchLabels:
      name: node-app-pod
      app: node-application
  template:
    metadata:
      name: node-app-pod
      labels:
        name: node-app-pod
        app: node-application
    spec:
      containers:
      - name: node-app
        image: mohanaveluk/	memberapp-ex:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
